### PR TITLE
Add demo in gh-pages

### PR DESCRIPTION
**Pull request by npm1**
For https://github.com/w3c/longtasks/issues/92

### CODE REVIEW

**Comment by npm1** [comment]
Oh this branch is not protected :O merging :)

**Comment by dashed** [comment]
@npm1 It looks like a deploy deleted the demos added in this PR in https://github.com/w3c/longtasks/commit/43e86bf7732f1379f6cebe02e1441b52f861d388

**Comment by npm1** [comment]
Oh no... I don't understand why it deletes all other files :( maybe I'll put it on a glitch lol

**Comment by npm1** [comment]
Ok should be fixed now sorry

**Pull request merged**
